version: "3"

includes:
  istio:
    taskfile: ./examples/istio
    dir: ./examples/istio
  simple-api:
    taskfile: ./examples/simple-api
    dir: ./examples/simple-api

tasks:
  devenv-init:
    desc: create podman machine and minikube cluster
    dir: ./
    cmds:
      - touch "$(pwd)/devenv-minikube-config"
      - export "KUBECONFIG=$(pwd)/devenv-minikube-config"
      - podman machine init --cpus=2 --memory=5120  
      - podman machine set --rootful
      - podman machine start
      - minikube start --cpus=2 --memory=4096 --addons=ingress --driver=podman --container-runtime=containerd --profile devenv

  devenv-init-large:
    desc: create podman machine and minikube cluster with extra resources
    dir: ./
    cmds:
      - touch "$(pwd)/devenv-minikube-config"
      - export "KUBECONFIG=$(pwd)/devenv-minikube-config"
      - podman machine init --cpus=4 --memory=18432 
      - podman machine set --rootful
      - podman machine start
      - minikube start --cpus=4 --memory=16384 --driver=podman --container-runtime=containerd --profile devenv
  
  devenv-minikube-start:
    desc: start minikube cluster
    cmds:
      - minikube start --driver=podman --container-runtime=containerd --profile devenv

  devenv-minikube-stop:
    desc: stop minikube cluster
    cmds:
      - minikube stop --profile devenv
      
  devenv-destroy:
    desc: destroys all minikube clusters and the podman machine
    deps: [devenv-minikube-stop]
    dir: ./
    cmds:
      - minikube delete --all
      - podman machine stop
      - podman machine rm -f
      - rm devenv-minikube-config

  devenv-status:
    desc: check status of dev environment
    cmds:
      - podman system connection list
      - podman machine list
      - minikube status --profile devenv

  devenv-hung:
    desc: minikube not responding
    dir: ./
    preconditions:
      - "[[ $(ps aux | grep podman | grep -v grep | wc -l) -gt 0 ]]"
    cmds:
      - ps aux | grep podman | grep -v grep | awk '{print $2}' | xargs kill
      - podman machine rm -f
      - minikube delete --all
      - rm devenv-minikube-config

  devenv-dashboard:
    desc: start minikube dashboard
    cmds:
      - minikube addons enable metrics-server --profile devenv
      - minikube dashboard --profile devenv

  default:
    desc: check status of dev environment
    deps: [devenv-status]

  