version: "3"

includes:
  istio:
    taskfile: ./examples/istio
    dir: ./examples/istio
  simple-api:
    taskfile: ./examples/simple-api
    dir: ./examples/simple-api

tasks:
  devenv-init:
    desc: create podman machine and minikube cluster
    dir: ./
    platforms: [darwin]
    cmds:
      - touch "$(pwd)/devenv-minikube-config"
      - export "KUBECONFIG=$(pwd)/devenv-minikube-config"
      - podman machine init --cpus=2 --memory=5120  
      - podman machine set --rootful
      - podman machine start
      - minikube start --cpus=2 --memory=4096 --addons=ingress --driver=podman --container-runtime=containerd --profile devenv
  
  devenv-init-chromeOS:
    desc: create minikube cluster
    dir: ./
    platforms: [linux]
    cmds:
      - sudo usermod --add-subuids 100000-165535 --add-subgids 100000-165535 $USER
      - sudo mkdir -p /etc/containers
      - sudo cp policy.json /etc/containers/
      - export PODMAN_IGNORE_CGROUPSV1_WARNING=true
      - podman system migrate
      - touch "$(pwd)/devenv-minikube-config"
      - export "KUBECONFIG=$(pwd)/devenv-minikube-config"
      - sudo adduser $USER libvirt
      - echo -e "user = \"root\"\ngroup = \"root\"\nremember_owner = 0\nnamespaces = []" > qemu.conf
      - sudo chown root:root qemu.conf
      - sudo chmod 600 qemu.conf
      - sudo cp qemu.conf /etc/libvirt/qemu.conf
      - sudo rm qemu.conf
      - minikube start --cpus=4 --memory=4096 --addons=ingress --driver=kvm2 --profile devenv
  

  devenv-init-large:
    desc: create podman machine and minikube cluster with extra resources
    dir: ./
    platforms: [darwin]
    cmds:
      - touch "$(pwd)/devenv-minikube-config"
      - export "KUBECONFIG=$(pwd)/devenv-minikube-config"
      - podman machine init --cpus=4 --memory=18432 
      - podman machine set --rootful
      - podman machine start
      - minikube start --cpus=4 --memory=16384 --driver=podman --container-runtime=containerd --profile devenv
  
  devenv-minikube-start:
    desc: start minikube cluster
    platforms: [darwin]
    cmds:
      - minikube start --driver=podman --container-runtime=containerd --profile devenv

  devenv-minikube-stop:
    desc: stop minikube cluster
    platforms: [darwin]
    cmds:
      - minikube stop --profile devenv
      
  devenv-destroy:
    desc: destroys all minikube clusters and the podman machine
    deps: [devenv-minikube-stop]
    dir: ./
    platforms: [darwin]
    cmds:
      - minikube delete --all
      - podman machine stop
      - podman machine rm -f
      - rm devenv-minikube-config

  devenv-destroy-chromeOS:
    desc: destroys all minikube clusters and the podman machine
    deps: [devenv-minikube-stop]
    dir: ./
    platforms: [linux]
    cmds:
      - minikube delete --all
      - rm devenv-minikube-config    

  devenv-status:
    desc: check status of dev environment
    cmds:
      - podman system connection list
      - podman machine list
      - minikube status --profile devenv

  devenv-hung:
    desc: minikube not responding
    dir: ./
    platforms: [darwin]
    preconditions:
      - "[[ $(ps aux | grep podman | grep -v grep | wc -l) -gt 0 ]]"
    cmds:
      - ps aux | grep podman | grep -v grep | awk '{print $2}' | xargs kill
      - podman machine rm -f
      - minikube delete --all
      - rm devenv-minikube-config

  devenv-dashboard:
    desc: start minikube dashboard
    cmds:
      - minikube addons enable metrics-server --profile devenv
      - minikube dashboard --profile devenv

  default:
    desc: check status of dev environment
    deps: [devenv-status]

  
