version: "3"

tasks:
  devenv-init:
    desc: create podman machine and minikube cluster
    cmds:
      - touch ~/.kube/devenv-minikube-config
      - export KUBECONFIG=~/.kube/devenv-minikube-config
      - podman machine init
      - podman machine start
      - minikube start --driver=podman --container-runtime=containerd --profile devenv
  
  devenv-minikube-start:
    desc: start minikube cluster
    cmds:
      - minikube start --driver=podman --container-runtime=containerd --profile devenv

  devenv-minikube-stop:
    desc: stop minikube cluster
    cmds:
      - minikube stop --profile devenv
      
  devenv-destroy:
    desc: destroys all minikube clusters and the podman machine
    deps: [devenv-minikube-stop]
    cmds:
      - minikube delete --all
      - podman machine stop
      - podman machine rm -f

  devenv-status:
    desc: check status of dev environment
    cmds:
      - podman system connection list
      - podman machine list
      - minikube status --profile devenv

  devenv-hung:
    desc: minikube not responding
    cmds:
      - "[[ \"$(uname -s)\" == \"Darwin\" ]] && ps aux | grep podman | grep -v grep | awk '{print $2}' | xargs kill"
      - podman machine rm -f
      - minikube delete --all

  devenv-dashboard:
    desc: start minikube dashboard
    cmds:
      - minikube addons enable metrics-server --profile devenv
      - minikube dashboard --profile devenv

  default:
    desc: check status of dev environment
    deps: [devenv-status]
