---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
  labels:
    app: myapi
spec:
  selector:
    matchLabels:
      app: myapi
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: myapi
    spec:
      containers:
        - name: simple-api
          image: simple-api
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: simple-api
  namespace: default
spec:
  selector:
    app: myapi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
