---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp-deployment
  labels:
    app: simple-webapp
spec:
  selector:
    matchLabels:
      app: simple-webapp
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: simple-webapp
    spec:
      containers:
        - name: simple-webapp
          image: simple-webapp
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: simple-webapp-svc
  namespace: default
spec:
  selector:
    app: simple-webapp
  ports:
    - port: 8080              # The port that the service will listen on internally within the cluster.
      targetPort: 80          # The port on the Pod that the service will forward traffic to.
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: simple-webapp-127-0-0-1.nip.io
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: simple-webapp-svc
              port: 
                number: 8080